### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by vinaydate** [fhelwanger/ocaml-on-windows#11]
My OS is Windows 10 Pro, Version 1703, OS build 15063.540

I have installed Windows Subsystem for Linux and NPM

I tried to install this repo, but installation failed with following error.

> npm install -g ocaml-on-windows

> ocaml-on-windows@0.0.1 preinstall C:\Program Files\nodejs\node_modules\ocaml-on-windows
> bin\preinstall.bat

"Installing ocaml..."
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
"Configuring opam..."
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
"Installing reason..."
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ocaml-on-windows@0.0.1 preinstall: `bin\preinstall.bat`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ocaml-on-windows@0.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vinay\AppData\Roaming\npm-cache\_logs\2017-08-09T11_53_09_966Z-debug.log

**The log file is as follows:**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ocaml-on-windows' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session c78648abed7ef7fb
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/ocaml-on-windows 638ms
8 silly pacote tag manifest for ocaml-on-windows@latest fetched in 901ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule ocaml-on-windows@0.0.1 checking installable status
14 silly currentTree nodejs
15 silly idealTree nodejs
15 silly idealTree `-- ocaml-on-windows@0.0.1
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add ocaml-on-windows@0.0.1
19 silly decomposeActions action count 8
20 silly decomposeActions fetch ocaml-on-windows@0.0.1
21 silly decomposeActions extract ocaml-on-windows@0.0.1
22 silly decomposeActions preinstall ocaml-on-windows@0.0.1
23 silly decomposeActions build ocaml-on-windows@0.0.1
24 silly decomposeActions install ocaml-on-windows@0.0.1
25 silly decomposeActions postinstall ocaml-on-windows@0.0.1
26 silly decomposeActions finalize ocaml-on-windows@0.0.1
27 silly decomposeActions refresh-package-json ocaml-on-windows@0.0.1
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir C:\Users\Vinay\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
31 verbose lock using C:\Users\Vinay\AppData\Roaming\npm-cache\_locks\staging-dfd8fbf9c1feea0f.lock for C:\Program Files\nodejs\node_modules\.staging
32 silly doParallel extract 8
33 silly extract ocaml-on-windows@0.0.1
34 silly doReverseSerial unbuild 8
35 silly doSerial remove 8
36 silly doSerial move 8
37 silly doSerial finalize 8
38 silly finalize C:\Users\Vinay\AppData\Roaming\nvm\v8.2.1\node_modules\ocaml-on-windows
39 silly doParallel refresh-package-json 8
40 silly refresh-package-json C:\Users\Vinay\AppData\Roaming\nvm\v8.2.1\node_modules\ocaml-on-windows
41 silly doParallel preinstall 8
42 silly preinstall ocaml-on-windows@0.0.1
43 info lifecycle ocaml-on-windows@0.0.1~preinstall: ocaml-on-windows@0.0.1
44 verbose lifecycle ocaml-on-windows@0.0.1~preinstall: unsafe-perm in lifecycle true
45 verbose lifecycle ocaml-on-windows@0.0.1~preinstall: PATH: C:\Users\Vinay\AppData\Roaming\nvm\v8.2.1\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\ocaml-on-windows\node_modules\.bin;C:\Program Files\nodejs\node_modules\.bin;G:\cmder\vendor\conemu-maximus5\ConEmu\Scripts;G:\cmder\vendor\conemu-maximus5;G:\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Fuse\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\Vinay\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\dotnet\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Yarn\bin;C:\Users\Vinay\AppData\Local\Programs\Python\Python36;C:\Program Files (x86)\Elm Platform\0.17.1\bin;C:\Users\Vinay\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin;C:\Users\Vinay\.dnx\bin;g:\Vinay\Projects\;PATH=C:\ProgramData\Oracle\Java\javapath;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\bin;C:\Program Files (x86)\Microsoft;C:\Users\Vinay\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Vinay\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Amazon\AWSCLI;C:\Users\Vinay\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\Vinay\AppData\Local\Yarn\bin
46 verbose lifecycle ocaml-on-windows@0.0.1~preinstall: CWD: C:\Program Files\nodejs\node_modules\ocaml-on-windows
47 silly lifecycle ocaml-on-windows@0.0.1~preinstall: Args: [ '/d /s /c', 'bin\\preinstall.bat' ]
48 silly lifecycle ocaml-on-windows@0.0.1~preinstall: Returned: code: 1  signal: null
49 info lifecycle ocaml-on-windows@0.0.1~preinstall: Failed to exec preinstall script
50 verbose unlock done using C:\Users\Vinay\AppData\Roaming\npm-cache\_locks\staging-dfd8fbf9c1feea0f.lock for C:\Program Files\nodejs\node_modules\.staging
51 verbose stack Error: ocaml-on-windows@0.0.1 preinstall: `bin\preinstall.bat`
51 verbose stack Exit status 1
51 verbose stack     at EventEmitter.<anonymous> (C:\Users\Vinay\AppData\Roaming\nvm\v8.2.1\node_modules\npm\lib\utils\lifecycle.js:289:16)
51 verbose stack     at emitTwo (events.js:125:13)
51 verbose stack     at EventEmitter.emit (events.js:213:7)
51 verbose stack     at ChildProcess.<anonymous> (C:\Users\Vinay\AppData\Roaming\nvm\v8.2.1\node_modules\npm\lib\utils\spawn.js:40:14)
51 verbose stack     at emitTwo (events.js:125:13)
51 verbose stack     at ChildProcess.emit (events.js:213:7)
51 verbose stack     at maybeClose (internal/child_process.js:921:16)
51 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
52 verbose pkgid ocaml-on-windows@0.0.1
53 verbose cwd C:\Users\Vinay
54 verbose Windows_NT 10.0.15063
55 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ocaml-on-windows"
56 verbose node v8.2.1
57 verbose npm  v5.3.0
58 error code ELIFECYCLE
59 error errno 1
60 error ocaml-on-windows@0.0.1 preinstall: `bin\preinstall.bat`
60 error Exit status 1
61 error Failed at the ocaml-on-windows@0.0.1 preinstall script.
61 error This is probably not a problem with npm. There is likely additional logging output above.
62 verbose exit [ 1, true ]

**Comment by fhelwanger** [comment]
I think I fixed it in 8a3ce42. Could you please try installing from master?

```
npm install -g fhelwanger/ocaml-on-windows
```

**Comment by vinaydate** [comment]
Worked. Thanks. I did not know the difference between

```npm install -g fhelwanger/ocaml-on-windows```

and 

``` npm install -g ocaml-on-windows```

**Comment by fhelwanger** [comment]
`npm install githubname/reponame` is just a shortcut to install directly from a github repo (more info on https://docs.npmjs.com/cli/install).

I'll publish a new version to npm soon, then it won't be necessary.

**Comment by vinaydate** [comment]
Now the installation proceeds, but there are errors after a while. (When I said, 'worked' earlier, I did not wait for installation to complete.) Error list is long. So mentioning sample of them:

[ERROR] Your version of OPAM (1.1.1) is not recent enough to read ~/.opam/repo/default/packages/clangml/clangml.3.9.1/opam. Upgrade OPAM to a more recent version (at least 1.2) to read this file correctly.

 Please run 'opam init' first to initialize the state of OPAM.
'opam switch 4.04.0' failed.

**Comment by fhelwanger** [comment]
My `opam --version` prints `1.2.2`.

Could you please try to `sudo apt-get update` inside bash then try again?

**Comment by vinaydate** [comment]
So, finally, things got installed, after ```sudo apt-get update```. Both ocaml and opam are of proper versions.

I am using VSCode. But there are no type annotations visible. Any specific configuration needed for VSCode to fully utilize reason extension? Tried to set paths in ```reason.path.*``` but it did not help.

P.S. Ocaml 4.04.0

**Comment by fhelwanger** [comment]
Nice, thanks for trying! I'll include `apt-get update` in next versions.

Actually, there's this issue that's preventing the reason vscode extension to work properly on windows: https://github.com/freebroccolo/ocaml-language-server/issues/27

If want to try it right now, you can fix it on your machine. Go to `%userprofile%\.vscode\extensions\freebroccolo.reasonml-0.0.99\node_modules\ocaml-language-server\out\src\server\session\` and edit `environment.js` changing the line:

```js
if (this.preamble != null) {
```

to

```js
if (false && this.preamble != null) {
```

**Comment by vinaydate** [comment]
Appreciate your help

**Comment by jgrosso** [comment]
@fhelwanger Thanks for the fix!
Quick question: should the manual workaround be `if (false && this.premable != null) {` (i.e. adding `false &&` instead of `false ||`)?

**Comment by fhelwanger** [comment]
@jgrosso `false ||` would just evaluate whatever comes after `||`, thus would have no effect at all.

I suggested adding `false &&` to make it never evaluate to `true`. It'll always be `false` no matter what the second operator is. This way, you don't need to delete the reason extension's code. If you need to change it back for whatever reason, you can always just delete that `false &&` :wink:

**Comment by fhelwanger** [comment]
@jgrosso Oh, I got it now, I put it wrong on my instructions above 😄 

Sorry about that, you're right. Thanks for pointing out!

**Comment by jgrosso** [comment]
No worries, thanks for posting the fix, and thanks for all your work to make OCaml and ReasonML work on Windows!

**Comment by vinaydate** [comment]
Please Help.

[https://github.com/reasonml/reasonml.github.io/issues/195#issuecomment-361028457](url)

**Update:** For unknown reasons, another try for ```npm install -g fhelwanger/ocaml-reason-wsl``` ran successfully, and I am able to do ReasonML on windows now.
