### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by fhelwanger** [fhelwanger/ocaml-on-windows#16]
This project is actually ocaml on bash on ubuntu on windows 😄 

Maybe it should be renamed to something like: `ocaml-on-wsl-on-windows`

cc @superherointj

**Comment by superherointj** [comment]
WSL (Windows Subsystem for Linux) is the name Microsoft gives to that project and is widely understood. The end goal is having reason. Maybe instead of OCaml, Bucklescript or Reason would be desirable instead. But it's up to you. It's your pick. :-)

**Comment by ghost** [comment]
I agree that a name change could be useful here. I'd probably try to go with something short like `wsl-ocaml`.

**Comment by superherointj** [comment]
For current version without 'bs-platform': "ocaml-wsl" sounds great. 
Reason for ocaml at beginning is to have a nice name order on meaningful keyword. WSL is attribute.
If 'bs-platform' is added, it should be something with BuckleScript: 
bucklescript-wsl (or reason-wsl?)

**Comment by fhelwanger** [comment]
Maybe `reason-cli-wsl`?

cc @chenglou

**Comment by chenglou** [comment]
reason-cli doesn't include bucklescript. This is probably a good thing. Either `ocaml-on-wsl`, `ocaml-reason-on-wsl`, or something like that is fine =)

**Comment by fhelwanger** [comment]
I like `ocaml-reason-on-wsl`, it very clear that both ocaml and reason are included and also that it runs on WSL.

**Comment by fhelwanger** [comment]
Done!

```
npm install -g ocaml-reason-wsl
```

ocaml-on-windows is deprecated
