### ISSUE TITLE
Add 'wsl' suffix to shortcut names to avoid conflicts w/ native version of apps

### ISSUE THREAD

**Issue by superherointj** [fhelwanger/ocaml-on-windows#19]
'ocaml-reason-wsl' is shadowing bs-platform on Windows native, and also Merlin, which influences on using the native windows versions. Would be desirable not conflicting with native version by adding a prefix like 'wsl':
`bsb -> bsbwsl`

**Comment by fhelwanger** [comment]
I'd like to wait until https://github.com/reasonml-editor/vscode-reasonml/issues/113 is done to look into this.
